const blogroll = [
  {
    name: "Rijk van Zanten",
    username: "rijkvanzanten",
    website: "https://rijks.website/",
    bio: "Rijk is the Lead Developer at Monospace Inc where he builds the Directus Suite. He was my study buddy during the first year at CMD Amsterdam. He since moved to the United States.",
    avatar: "https://unavatar.now.sh/github/rijkvanzanten",
  },
  {
    name: "Titus Wormer",
    username: "wooorm",
    website: "https://wooorm.com/",
    bio: "Titus works full-time on open source maintaining 400+ projects that are downloaded 3B+ times a year. Most of his work is as a core team member of unified. He was one of my former instructors at CMD Amsterdam and one of the main reasons I started teaching at the same program.",
    avatar: "https://unavatar.now.sh/github/wooorm",
  },
  {
    name: "Laurens Aarnoudse",
    username: "razpudding",
    website: "https://codepen.io/Razpudding/",
    bio: "Laurens is a fellow teacher at CMD Amsterdam, developer and a lot of other things. Interested in datavisualisation, ethics, sustainability, and the world in general. He sometimes use the Random Industries brand to take on creative challenges.",
    avatar: "https://avatars1.githubusercontent.com/u/8708858?s=460&u=81cbb12e681dd4b6bca2f0cdeea4e5ad8a9a6445&v=4",
  },
  {
    name: "Daan Rongen",
    username: "daanrongen",
    website: "https://daan.website/",
    bio: "Daan uses computational power to enhance everyday objects, places, and experiences working at data visualization agency CLEVERºFRANKE. Fellow student and later fellow freelance teacher for a short while.",
    avatar: "https://unavatar.now.sh/github/daanrongen",
  },
  {
    name: "Daniel Shiffman",
    username: "shiffman",
    website: "https://shiffman.net/",
    bio: "Daniel Shiffman works as an Associate Arts Professor at the Interactive Telecommunications Program at NYU’s Tisch School of the Arts. But he's probably better known for his Youtube channel 'The Coding Train', a great inspiration for my own teaching..",
    avatar: "https://unavatar.now.sh/github/shiffman",
  },
  {
    name: "Derek Sivers",
    username: "sivers",
    website: "https://sivers.org/",
    bio: "Derek Sivers is an American writer, musician, programmer and entrepreneur. His blog is probably the most thought-provoking blog I follow.",
    avatar: "https://unavatar.now.sh/github/sivers",
  },
  {
    name: "Max Böck",
    username: "mxbck",
    website: "https://mxb.dev/",
    bio: "Max Böck is a front-end web developer and designer based in Vienna, Austria. He's been building stuff on the web for the last 12 years, working with clients across various countries and industries. He was the first to introduce me to the Indieweb concept and the whole reason I started working on my personal site.",
    avatar: "https://unavatar.now.sh/mxbck",
  },
  {
    name: "Mike Monteiro",
    username: "monteiro",
    website: "https://muledesign.com/",
    bio: "Mike Monteiro is the co-founder and design director of Mule Design. He prefers that designers have strong spines. Mike writes and speaks frequently about the craft, ethics, and business of design. He's the one that made me realize design ethics was a thing.",
    avatar: "https://unavatar.now.sh/monteiro",
  },
  {
    name: "Cassie Evans",
    username: "cassiecodes",
    website: "https://www.cassie.codes/",
    bio: "Cassie makes things on the web. During the week she makes accessible, progressively enhanced things for Clearleft and in her spare fun, animated things on Codepen. She brings the fun back into development.",
    avatar: "https://unavatar.now.sh/cassiecodes",
  },
  {
    name: "Cassidy Williams",
    username: "cassidoo",
    website: "https://cassidoo.co/",
    bio: "Cassidy is an instructor and senior software engineer at React Training. Before now, she worked at CodePen, Amazon, L4 Digital, Clarifai, and Venmo, and graduated from Iowa State University. Her TikTok style video's on Twitter are the best.",
    avatar: "https://unavatar.now.sh/github/cassidoo",
  },
  {
    name: "Tatiana Mac",
    username: "tatianamac",
    website: "https://tatianamac.com/",
    bio: "Tatiana Mac (she/they) is an independent American deseloper (designer, then developer). She is an open source maintainer who created and is building Self-Defined, a modern dictionary about us",
    avatar: "https://unavatar.now.sh/github/tatianamac",
  },
  {
    name: "Matthew Rayfield",
    username: "Matthew Rayfield",
    website: "https://matthewrayfield.com/",
    bio: "All-round creative guy.",
    avatar: "https://unavatar.now.sh/github/MatthewRayfield",
  },
  {
    name: "Andy Bell",
    username: "piccalilli_",
    website: "https://piccalil.li",
    bio: "Andy Bell is an educator who focuses on design, front-end development, accessibility and progressive enhancement. He teaches at Piccalilli and Front-End Challenges Club.",
    avatar: "https://unavatar.now.sh/github/hankchizljaw",
  },
  {
    name: "Zach Leatherman",
    username: "zachleat",
    website: "https://www.zachleat.com/",
    bio: "Zach is a Builder for the web with Netlify. He’s currently fixated on web fonts and static site generators. His public speaking résumé includes talks in eight different countries.",
    avatar: "https://unavatar.now.sh/github/zachleat",
  },
  {
    name: "Reinier Ladan",
    username: "reinier",
    website: "https://reinierladan.nl/",
    bio: "Reinier creates excellent digital products by managing product teams, designing user interfaces, and even developing prototypes. He's been doing that since the ’90s.",
    avatar: "https://unavatar.now.sh/github/Reinier",
  },
  {
    name: "Laura Kalbag",
    username: "laurakalbag",
    website: "https://laurakalbag.com/",
    bio: " Laura Kalbag is a designer and British person, now living in Cork, Ireland. She wrote a book about web accessibility called Accessibility For Everyone and co-founder of Small Technology Foundation.",
    avatar: "https://unavatar.now.sh/github/LauraKalbag",
  },
  {
    name: "Rick Pastoor",
    username: "rickpastoor",
    website: "https://rickpastoor.com/",
    bio: "Rick is the author of Dutch bestseller GRIP. It’s his mission to help you and me make smarter choices. Spending a lot of time thinking about this and discussing ideas and solutions with people.",
    avatar: "https://unavatar.now.sh/github/rickpastoor",
  },
  {
    name: "Daniël Verlaan",
    username: "danielverlaan",
    website: "https://daniel.verlaan.xyz/",
    bio: "Daniel is a tech journalist at RTL Nieuws, where he makes stories about technology for television and the internet. Think about hackers, cyber crime and data leaks, but also smartphones, smart vacuum cleaners and asymmetric encryption.",
    avatar: "https://unavatar.now.sh/github/danielverlaan",
  },
  {
    name: "Frank Chimero",
    username: "frank_chimero",
    website: "https://frankchimero.com/",
    bio: "Frank is a New Yorker with a love for pizza, museums, playlists, natural wines, and Phil Collins. (Nobody’s perfect.) For the past 15 years, he worked as a designer across brand, interactive, and editorial projects.",
    avatar: "https://unavatar.now.sh/frankchimero.com",
  },
  {
    name: "Craig Mod",
    username: "craigmod",
    website: "https://craigmod.com/",
    bio: "Craig is a walker + writer + photographer who loves books and publishing, sends the Roden & Ridgeline newsletters, hosts the On Margins podcast,and explores old mountain paths. He's based in Japan.",
    avatar: "https://unavatar.now.sh/craigmod.com",
  },
  {
    name: "Hidde de Vries",
    username: "hdv",
    website: "https://hiddedevries.nl/en/",
    bio: "Hidde is a front-end web developer who prioritises what users see and interact with. To him, accessibility and performance are essential aspects of building front-ends. ",
    avatar: "https://unavatar.now.sh/hiddedevries.nl/",
  },
  {
    name: "Chris Coyier",
    username: "chriscoyier",
    website: "https://chriscoyier.net/",
    bio: "Chris is a web designer and developer. He built CSS-Tricks, a website all about building websites, going strong for 10 years. He's the co-founder of CodePen, a playground for front-end web development.",
    avatar: "https://unavatar.now.sh/chriscoyier",
  },
  {
    name: "Brad Frost",
    username: "brad_frost",
    website: "https://bradfrost.com/",
    bio: "Brad is a web designer, speaker, consultant, writer, and musician located in beautiful Pittsburgh, PA. He wrote a book called Atomic Design, which covers all that goes into creating and maintaining effective design systems.",
    avatar: "https://unavatar.now.sh/brad_frost",
  },
  {
    name: "Wes Bos",
    username: "wesbos",
    website: "https://wesbos.com/",
    bio: "Wes is a full stack web developer and designer from Hamilton, Canada. He loves to share what he knows through his training products, teaching and speaking at conferences. He's been creating on the web for around 9 years and has become pretty good at it.",
    avatar: "https://unavatar.now.sh/github/wesbos",
  },
  {
    name: "Adrian Roselli",
    username: "aardrian",
    website: "https://adrianroselli.com/",
    bio: "Adrian has been developing accessible, effective user interfaces for the Web since 1993, as well as interfaces for multimedia and software applications. With a focus on standards and accessibility, he ensures software and web-based applications can be utilized by users with varying levels of ability on a wide array of platforms. ",
    avatar: "https://unavatar.now.sh/github/aardrian",
  },
  {
    name: "Dave Rupert",
    username: "davatron5000",
    website: "https://daverupert.com/",
    bio: "Dave is lead developer at Paravel and co-host of ShopTalk, an award-winning sound effects podcast that also covers web development. He lives n Austin, TX; the best damn city, in the best damn state, in the best damn country, in the whole damn world.",
    avatar: "https://unavatar.now.sh/github/davatron5000",
  },
  {
    name: "Ethan Marcotte",
    username: "beep",
    website: "https://ethanmarcotte.com/",
    bio: "Ethan is an independent web designer, writer, and speaker. He's also the fellow who started that whole “responsive design” thing. He helpes organizations design and build better sites and services, and ensures they can be accessed by everyone, everywhere.",
    avatar: "https://unavatar.now.sh/github/beep",
  },
  {
    name: "Jeffrey Zeldman",
    username: "zeldman",
    website: "https://www.zeldman.com/",
    bio: "Jeffrey publishes A List Apart “for people who make websites,” a leading journal of web and interaction design thought, and co-founded the multi-city user experience design conference An Event Apart with Eric Meyer.",
    avatar: "https://unavatar.now.sh/github/zeldman",
  },
  {
    name: "Jeremy Keith",
    username: "adactio",
    website: "https://adactio.com/",
    bio: "Jeremy is an irish developer making websites. He works in Brighton at Clearleft, a design agency he co-founded back in 2005.",
    avatar: "https://unavatar.now.sh/github/adactio",
  },
  {
    name: "Sara Soueidan",
    username: "SaraSoueidan",
    website: "https://www.sarasoueidan.com/",
    bio: "Sara is a  freelance front-end UI developer and trainer specializing in responsive Web design, modern CSS, progressive enhancement, and accessibility. She works with my clients to create interfaces and design systems that work for everyone.",
    avatar: "https://unavatar.now.sh/github/SaraSoueidan",
  },
  {
    name: "Naval Ravikant",
    username: "naval",
    website: "https://nav.al",
    bio: "Naval Ravikant is an Indian-American entrepreneur and investor. He is the co-founder, chairman and former CEO of AngelList.",
    avatar: "https://unavatar.now.sh/nav.al",
  },
  {
    name: "Josh W. Comeau",
    username: "JoshWComeau",
    website: "https://www.jason.af",
    bio: "Software developer. Makes stuff.",
    avatar: "https://unavatar.now.sh/github/JoshWComeau",
  },
    {
    name: "Matt Mullenweg",
    username: "photomatt",
    website: "https://ma.tt",
    bio: "My name is Matthew Mullenweg. I was born and raised in Houston, Texas. I write code, prose, and music. I love taking photos.I am a founding developer of WordPress, the Open Source software used by over 31% of the web.",
    avatar: "https://unavatar.now.sh/github/m",
  },
  {
    name: "Stephanie Eckles",
    username: "5t3ph",
    website: "https://thinkdobecreate.com",
    bio: "Girl Geek, front-end focused software engineer, publishing a video series for beginner developers, authoring ModernCSS.dev, creator of Style Stage, providing Eleventy resources on 11ty.Rocks, and mom of two girls.",
    avatar: "https://unavatar.now.sh/github/5t3ph",
  },
    {
    name: "Brian Lovin",
    username: "brian_lovin",
    website: "https://brianlovin.com",
    bio: "I’m a product designer, podcaster, and writer, currently living in San Francisco. Right now I’m designing native mobile apps at GitHub. Before GitHub, I co-founded Spectrum, a platform for large-scale communities to have better public conversations.",
    avatar: "https://unavatar.now.sh/brian_lovin",
  },
  {
    name: "Paul Stamatiou",
    username: "stammy",
    website: "https://paulstamatiou.com",
    bio: "I'm a designer at Twitter in New York. Technology has often found ways to pull me into new hobbies. I got into photography out of a curiosity for DSLR cameras.",
    avatar: "https://unavatar.now.sh/github/stammy",
  },
  {
    name: "Robin Rendle",
    username: "robinrendle",
    website: "https://www.robinrendle.com",
    bio: "I’m from the south-west of England, but now I live in cloudy San Francisco where I design things at Sentry whilst I blog alongside the ever-so-lovely team at CSS-Tricks.",
    avatar: "https://unavatar.now.sh/github/robinrendle",
  },
  {
    name: "Julia Evans",
    username: "b0rk",
    website: "https://jvns.ca",
    bio: "I’m a software developer. I live in Montreal. I sometimes give talks. Most of my income comes from my programming zines business Wizard Zines.",
    avatar: "https://unavatar.now.sh/github/jvns",
  },
  {
    name: "Jelmer de Boer",
    username: "jelmerdeboer",
    website: "https://jelmerdeboer.nl",
    bio: "Hoi, ik ben Jelmer de Boer en dit blog is mijn publieke dagboek over uiteenlopende onderwerpen. Je bent hier vast verzeild geraakt omdat je iets wilde lezen over fitness, eten, planten of vliegtickets.",
    avatar: "https://unavatar.now.sh/jelmerdeboer.nl",
  },
    {
    name: "Matt DesLauriers",
    username: "mattdesl",
    website: "https://www.mattdesl.com",
    bio: "I’m a 30 year old generative artist and creative coder from Toronto, Canada, and now based in London, UK.",
    avatar: "https://unavatar.now.sh/github/mattdesl",
  },
  {
    name: "Mr. Money Mustache",
    username: "mrmoneymustache",
    website: "https://www.mrmoneymustache.com",
    bio: "Mr. Money Mustache was a thirtysomething retiree who now writes about how we can all lead a frugal yet Badass life of leisure.",
    avatar: "https://unavatar.now.sh/mrmoneymustache.com",
  },
  {
    name: "Rasmus Andersson",
    username: "rsms",
    website: "https://rsms.me",
    bio: "My name is Rasmus Andersson. I’m a Swedish he/him living in San Francisco, California. Software is the medium through which I express myself.",
    avatar: "https://unavatar.now.sh/github/rsms",
  },
    {
    name: "Joel Califa",
    username: "notdetails",
    website: "http://joelcalifa.com",
    bio: "Joel is a professional problem solver. He builds teams, refines strategies, designs products, and codes things.",
    avatar: "https://unavatar.now.sh/joelcalifa.com",
  },
      {
    name: "Ernst-Jan Pfauth",
    username: "ejpfauth",
    website: "http://pfauth.com",
    bio: "Mede-oprichter en directeur van De Correspondent, een dagelijks medicijn tegen de waan van de dag. Host van Een Podcast over Media, samen met Alexander Klöpping.",
    avatar: "https://unavatar.now.sh/ejpfauth",
  },
]

module.exports = {
  blogroll
}
