const blogroll = [
  {
    name: "Rijk van Zanten",
    website: "https://rijks.website/",
    bio: "Rijk is the Lead Developer at Monospace Inc where he builds the Directus Suite. He was my study buddy during the first year at CMD Amsterdam. He since moved to the United States.",
    avatar: "https://avatars.io/twitter/rijkvanzanten",
  },
  {
    name: "Titus Wormer",
    website: "https://wooorm.com/",
    bio: "Titus works full-time on open source maintaining 400+ projects that are downloaded 3B+ times a year. Most of his work is as a core team member of unified. He was one of my former instructors at CMD Amsterdam and one of the main reasons I started teaching at the same program.",
    avatar: "https://avatars.io/twitter/wooorm",
  },
  {
    name: "Laurens Aarnoudse",
    website: "https://codepen.io/Razpudding/",
    bio: "Laurens is a fellow teacher at CMD Amsterdam, developer and a lot of other things. Interested in datavisualisation, ethics, sustainability, and the world in general. He sometimes use the Random Industries brand to take on creative challenges.",
    avatar: "https://avatars1.githubusercontent.com/u/8708858?s=460&u=81cbb12e681dd4b6bca2f0cdeea4e5ad8a9a6445&v=4",
  },
  {
    name: "Daan Rongen",
    website: "https://daan.website/",
    bio: "Daan uses computational power to enhance everyday objects, places, and experiences working at data visualization agency CLEVERºFRANKE. Fellow student and later fellow freelance teacher for a short while.",
    avatar: "https://avatars.io/twitter/daanrongen",
  },
  {
    name: "Ioannis (Janno) Kapritsias",
    website: "https://www.softsquare.nl/",
    bio: "Janno is a software developer at is own company Softsquare and fellow teacher at CMD Amsterdam teaching Front-end and Introduction to Programming.",
    avatar: "https://avatars.io/twitter/ioannisDevelop",
  },
  {
    name: "Daniel Shiffman",
    website: "https://shiffman.net/",
    bio: "Daniel Shiffman works as an Associate Arts Professor at the Interactive Telecommunications Program at NYU’s Tisch School of the Arts. But he's probably better known for his Youtube channel 'The Coding Train', a great inspiration for my own teaching..",
    avatar: "https://avatars.io/twitter/shiffman",
  },
  {
    name: "Derek Sivers",
    website: "https://sivers.org/",
    bio: "Derek Sivers is an American writer, musician, programmer and entrepreneur. His blog is probably the most thought-provoking blog I follow.",
    avatar: "https://avatars.io/twitter/sivers",
  },
  {
    name: "Max Böck",
    website: "https://mxb.dev/",
    bio: "Max Böck is a front-end web developer and designer based in Vienna, Austria. He's been building stuff on the web for the last 12 years, working with clients across various countries and industries. He was the first to introduce me to the Indieweb concept and the whole reason I started working on my personal site.",
    avatar: "https://avatars.io/twitter/mxbck",
  },
  {
    name: "Mike Monteiro",
    website: "https://muledesign.com/",
    bio: "Mike Monteiro is the co-founder and design director of Mule Design. He prefers that designers have strong spines. Mike writes and speaks frequently about the craft, ethics, and business of design. He's the one that made me realize design ethics was a thing.",
    avatar: "https://avatars.io/twitter/monteiro",
  },
  {
    name: "Cassie Evans",
    website: "https://www.cassie.codes/",
    bio: "Cassie makes things on the web. During the week she makes accessible, progressively enhanced things for Clearleft and in her spare fun, animated things on Codepen. She brings the fun back into development.",
    avatar: "https://avatars.io/twitter/cassiecodes",
  },
  {
    name: "Cassidy Williams",
    website: "https://cassidoo.co/",
    bio: "Cassidy is an instructor and senior software engineer at React Training. Before now, she worked at CodePen, Amazon, L4 Digital, Clarifai, and Venmo, and graduated from Iowa State University. Her TikTok style video's on Twitter are the best.",
    avatar: "https://avatars.io/twitter/cassidoo",
  },
  {
    name: "Tatiana Mac",
    website: "https://tatianamac.com/",
    bio: "Tatiana Mac (she/they) is an independent American deseloper (designer, then developer). She is an open source maintainer who created and is building Self-Defined, a modern dictionary about us",
    avatar: "https://avatars.io/twitter/TatianaTMac",
  },
  {
    name: "Matthew Rayfield",
    website: "https://matthewrayfield.com/",
    bio: "All-round creative guy.",
    avatar: "https://avatars.io/twitter/MatthewRayfield",
  },
  {
    name: "Andy Bell",
    website: "https://hankchizljaw.com/",
    bio: "Andy Bell is an educator who focuses on design, front-end development, accessibility and progressive enhancement. He teaches at Piccalilli and Front-End Challenges Club.",
    avatar: "https://avatars.io/twitter/hankchizljaw",
  },
  {
    name: "Zach Leatherman",
    website: "https://www.zachleat.com/",
    bio: "Zach is a Builder for the web with Netlify. He’s currently fixated on web fonts and static site generators. His public speaking résumé includes talks in eight different countries.",
    avatar: "https://avatars.io/twitter/zachleat",
  },
  {
    name: "Reinier Ladan",
    website: "https://reinierladan.nl/",
    bio: "Reinier creates excellent digital products by managing product teams, designing user interfaces, and even developing prototypes. He's been doing that since the ’90s.",
    avatar: "https://avatars.io/twitter/Reinier",
  },
  {
    name: "Laura Kalbag",
    website: "https://laurakalbag.com/",
    bio: " Laura Kalbag is a designer and British person, now living in Cork, Ireland. She wrote a book about web accessibility called Accessibility For Everyone and co-founder of Small Technology Foundation.",
    avatar: "https://avatars.io/twitter/LauraKalbag",
  },
  {
    name: "Rick Pastoor",
    website: "https://rickpastoor.com/",
    bio: "Rick is the author of Dutch bestseller GRIP. It’s his mission to help you and me make smarter choices. Spending a lot of time thinking about this and discussing ideas and solutions with people.",
    avatar: "https://avatars.io/twitter/rickpastoor",
  },
  {
    name: "Daniël Verlaan",
    website: "https://daniel.verlaan.xyz/",
    bio: "Daniel is a tech journalist at RTL Nieuws, where he makes stories about technology for television and the internet. Think about hackers, cyber crime and data leaks, but also smartphones, smart vacuum cleaners and asymmetric encryption.",
    avatar: "https://avatars.io/twitter/danielverlaan",
  },
  {
    name: "Frank Chimero",
    website: "https://frankchimero.com/",
    bio: "Frank is a New Yorker with a love for pizza, museums, playlists, natural wines, and Phil Collins. (Nobody’s perfect.) For the past 15 years, he worked as a designer across brand, interactive, and editorial projects.",
    avatar: "https://avatars.io/twitter/frank_chimero",
  },
  {
    name: "Craig Mod",
    website: "https://craigmod.com/",
    bio: "Craig is a walker + writer + photographer who loves books and publishing, sends the Roden & Ridgeline newsletters, hosts the On Margins podcast,and explores old mountain paths. He's based in Japan.",
    avatar: "https://avatars.io/twitter/craigmod",
  },
  {
    name: "Hidde de Vries",
    website: "https://hiddedevries.nl/en/",
    bio: "Hidde is a front-end web developer who prioritises what users see and interact with. To him, accessibility and performance are essential aspects of building front-ends. ",
    avatar: "https://avatars.io/twitter/hdv",
  },
  {
    name: "Chris Coyier",
    website: "https://chriscoyier.net/",
    bio: "Chris is a web designer and developer. He built CSS-Tricks, a website all about building websites, going strong for 10 years. He's the co-founder of CodePen, a playground for front-end web development.",
    avatar: "https://avatars.io/twitter/chriscoyier",
  },
  {
    name: "Brad Frost",
    website: "https://bradfrost.com/",
    bio: "Brad is a web designer, speaker, consultant, writer, and musician located in beautiful Pittsburgh, PA. He wrote a book called Atomic Design, which covers all that goes into creating and maintaining effective design systems.",
    avatar: "https://avatars.io/twitter/brad_frost",
  },
  {
    name: "Wes Bos",
    website: "https://wesbos.com/",
    bio: "Wes is a full stack web developer and designer from Hamilton, Canada. He loves to share what he knows through his training products, teaching and speaking at conferences. He's been creating on the web for around 9 years and has become pretty good at it.",
    avatar: "https://avatars.io/twitter/wesbos",
  },
  {
    name: "Adrian Roselli",
    website: "https://adrianroselli.com/",
    bio: "Adrian has been developing accessible, effective user interfaces for the Web since 1993, as well as interfaces for multimedia and software applications. With a focus on standards and accessibility, he ensures software and web-based applications can be utilized by users with varying levels of ability on a wide array of platforms. ",
    avatar: "https://avatars.io/twitter/aardrian",
  },
  {
    name: "Dave Rupert",
    website: "https://daverupert.com/",
    bio: "Dave is lead developer at Paravel and co-host of ShopTalk, an award-winning sound effects podcast that also covers web development. He lives n Austin, TX; the best damn city, in the best damn state, in the best damn country, in the whole damn world.",
    avatar: "https://avatars.io/twitter/davatron5000",
  },
  {
    name: "Ethan Marcotte",
    website: "https://ethanmarcotte.com/",
    bio: "Ethan is an independent web designer, writer, and speaker. He's also the fellow who started that whole “responsive design” thing. He helpes organizations design and build better sites and services, and ensures they can be accessed by everyone, everywhere.",
    avatar: "https://avatars.io/twitter/beep",
  },
  {
    name: "Jeffrey Zeldman",
    website: "https://www.zeldman.com/",
    bio: "Jeffrey publishes A List Apart “for people who make websites,” a leading journal of web and interaction design thought, and co-founded the multi-city user experience design conference An Event Apart with Eric Meyer.",
    avatar: "https://avatars.io/twitter/zeldman",
  },
  {
    name: "Jeremy Keith",
    website: "https://adactio.com/",
    bio: "Jeremy is an irish developer making websites. He works in Brighton at Clearleft, a design agency he co-founded back in 2005.",
    avatar: "https://avatars.io/twitter/adactio",
  },
  {
    name: "Sara Soueidan",
    website: "https://www.sarasoueidan.com/",
    bio: "Sara is a  freelance front-end UI developer and trainer specializing in responsive Web design, modern CSS, progressive enhancement, and accessibility. She works with my clients to create interfaces and design systems that work for everyone.",
    avatar: "https://avatars.io/twitter/sarasoueidan",
  },
  {
    name: "Sara Soueidan",
    website: "https://www.sarasoueidan.com/",
    bio: "Sara is a  freelance front-end UI developer and trainer specializing in responsive Web design, modern CSS, progressive enhancement, and accessibility. She works with my clients to create interfaces and design systems that work for everyone.",
    avatar: "https://avatars.io/twitter/sarasoueidan",
  },
]

module.exports = {
  blogroll
}
